language: node_js
cache: yarn

before_install:
  - npm i -g lerna

install:
  - yarn

script:
  - yarn build
  - yarn test

deploy:
  provider: script
  script: cd packages/website/ && yarn deploy
  on:
    branch: master

addons:
  chrome: stable
  browserstack:
    username: adriengrsmto
