language: node_js
cache: yarn

before_install:
  - npm i -g lerna
  - npm i -g gatsby-cli@5.4.0

install:
  - yarn

script:
  - yarn build
  - yarn test

deploy:
  provider: script
  script: cd packages/website/ && yarn deploy
  skip_cleanup: true
  on:
    branch: master

addons:
  chrome: stable
  browserstack:
    username: 'adriengrsmto'
    access_key:
      secure: 'D75arx7W8WEGPIDHbWNrvttP3kbT5u8w+QXXYAP/DNH3012BoThNLmIB9U8YAxOccrC0ZISQq8d73/aX70A0S97IJpFQv9wwIS540JwawKSJc23OeKNsImobeNdK0k2al8JvKonIaPJzexKTNHwV7OYxzFxIotGrIQsImjC38Pw='
